services:
  - type: web
    name: progettone-app
    env: python
    buildCommand: ""
    startCommand: gunicorn run:flask_app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your-secret-here
      - key: JWT_SECRET_KEY
        value: your-jwt-secret-here
      - key: DATABASE_URL
        fromDatabase:
          name: progettone-db
          property: connectionString

databases:
  - name: progettone-db
    databaseName: progettone
    user: postgres