"""init 

Revision ID: 19fc280830b6
Revises: 
Create Date: 2025-06-03 15:18:16.686766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fc280830b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=150), nullable=False),
    sa.Column('user_password', sa.String(length=256), nullable=False),
    sa.Column('user_admin', sa.Boolean(), nullable=False),
    sa.Column('user_descriptin', sa.String(length=256), nullable=True),
    sa.Column('user_goals', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_username')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('project_category', sa.String(length=150), nullable=False),
    sa.Column('project_description', sa.String(length=150), nullable=True),
    sa.Column('project_created', sa.DateTime(), nullable=True),
    sa.Column('project_updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
