"""mod su tabelle

Revision ID: 37ba48e0a014
Revises: ffbd843a3662
Create Date: 2025-06-16 15:25:53.679575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ba48e0a014'
down_revision = 'ffbd843a3662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
