"""mod su tabelle

Revision ID: 45db8f07fc98
Revises: 37ba48e0a014
Create Date: 2025-06-16 15:28:37.473019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45db8f07fc98'
down_revision = '37ba48e0a014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
