"""aggiunto campo project_img 

Revision ID: 46e725a90b2f
Revises: d8b6528d1800
Create Date: 2025-06-10 08:23:11.371868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e725a90b2f'
down_revision = 'd8b6528d1800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('project_img')

    # ### end Alembic commands ###
