"""Descrizione delle modifiche

Revision ID: 717d16310801
Revises: da6a17eb4c88
Create Date: 2025-06-16 15:06:02.617682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717d16310801'
down_revision = 'da6a17eb4c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
