"""aggiunta models per api 

Revision ID: d8b6528d1800
Revises: 19fc280830b6
Create Date: 2025-06-04 10:20:18.370385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b6528d1800'
down_revision = '19fc280830b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_jwt',
    sa.Column('userjwt_id', sa.Integer(), nullable=False),
    sa.Column('userjwt_username', sa.String(length=150), nullable=False),
    sa.Column('userjwt_password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('userjwt_id'),
    sa.UniqueConstraint('userjwt_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_jwt')
    # ### end Alembic commands ###
