"""Fix typo in user_description column

Revision ID: da6a17eb4c88
Revises: 77e8a2285d4f
Create Date: 2025-06-16 14:16:38.202756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6a17eb4c88'
down_revision = '77e8a2285d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_description', sa.String(length=256), nullable=True))
        batch_op.drop_column('user_descriptin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_descriptin', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('user_description')

    # ### end Alembic commands ###
