"""mod su tabelle

Revision ID: ffbd843a3662
Revises: 717d16310801
Create Date: 2025-06-16 15:21:14.431132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbd843a3662'
down_revision = '717d16310801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
